language: cpp
dist: trusty
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - gcc-6
            - git
            - libopencv-dev

before_script:
        - git submodule update --init --recursive
        - CXX="g++-6"
        - CC="gcc-6"

script:
        - mkdir build && cd build && cmake ..
        - make -j
